name: Package Addon

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Package
        run: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
